[build]
  base    = "mario-invite"
  command = "npm run build"
  publish = "mario-invite/dist"

[build.environment]
  NODE_VERSION = "20"

[[redirects]]
  from   = "/*"
  to     = "/index.html"
  status = 200
